apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mail-reset-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mail-reset-role
subjects:
- kind: ServiceAccount
  name: mail-reset
  namespace: default
